client_secret: -secret-key-32-
debug: false
disable_auto_update: true
disable_command_execute: false
disable_force_update: false
disable_nat: false
disable_send_query: false
gpu: false
#hard_drive_partition_allowlist: ''
insecure_tls: false
ip_report_period: 1800
#nic_allowlist: ''
report_delay: 4
self_update_period: 0
server: 127.0.0.1:8008
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: false
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: -uuid-
